{% set name = "rrdtool" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/oetiker/rrdtool-1.x/archive/v{{ version }}.tar.gz
  sha256: 405f4ce365e2e37bdeff9bbb844cbedf9b36dde7344b31449e369315a3df5ef0

build:
  number: 0
  skip: true  # [win]
  # Fails with "Bad CPU type in executable" when cross-compiling
  skip_compile_pyc:   # [osx and arm64]
    - share/rrdtool/examples/stripes.py  # [osx and arm64]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make
    - libtool
    - pkg-config
    # Required for "make check"
    - coreutils
    - bc
  host:
    - cairo
    - gettext
    - glib
    - libpng
    - libxml2
    - pango
  run:
    # Looks pretty stable
    # https://abi-laboratory.pro/index.php?view=timeline&l=pango
    - {{ pin_compatible('pango') }}

test:
  commands:
    - rrdtool --help

about:
  home: https://www.rrdtool.org
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: Round Robin Database Tool
  description: |
    RRDtool is a little program for easily maintaining a database of
    time-series data. It comes with a charting program for drawing
    pretty graphs based on the data stored.
  doc_url: https://www.rrdtool.org/doc/index.en.html
  dev_url: https://github.com/oetiker/rrdtool-1.x/

extra:
  recipe-maintainers:
    - chrisburr
